### ISSUE TITLE
Improve documnetation

### ISSUE THREAD

**Issue by Tetriz** [grumpyp/backlink-checker#1]
Hi! Thanks for doing this. We've just had a discussion with a friend of mine about a simple and nice backlink checker solution.
Your checker looks nice because as an input you can give a pair of "Donor-URL, Bbacklink-Target".

What is not clear - output. Does the checker checks if a backlink Do-/No-follow? Does the checker checks if a Donor-URL allowed to be indexed (robots.txt, meta robots)?

BTW, the mentioned above features - are very important for such checker.

**Comment by grumpyp** [comment]
Hi @Tetriz 

The tool doesn't check if the link is dofollow or nofollow because if you buy or exchange a link, this is predefined already.

About the donor-url I don't understand what you'd mean by that.

**Comment by Tetriz** [comment]
Hi @grumpyp 

> The tool doesn't check if the link is dofollow or nofollow because if you buy or exchange a link, this is predefined already.

The problem is that despite any agreements a dofollow can be changed later to nofollow. Exactly same reason as why a backlink can disappear - unfair people. This is basically the reason to have a backlink-checker: to monitor backlinks and its characteristics.

> About the donor-url I don't understand what you'd mean by that.

There is another issues with unfair people. E.g. you are getting a backlink from a donor-page and all looks good today. But few days/weeks later this page will either have a `<meta name="robots" content="noindex, nofollow" />` or will be forbidden to be indexed via robots.txt

**Comment by grumpyp** [comment]
Hi @Tetriz

that does make sense, I might add it as features.
Feel also free to open a new issue or even contribute.

Thanks for the input!
