### ISSUE TITLE
isnt it possible for the backlink checker to find the backlinks without txt file?

### ISSUE THREAD

**Issue by rohan2734** [grumpyp/backlink-checker#3]
isnt it possible for the backlink checker to find the backlinks without txt file?
that is how ahref, semrush and other tools work

**Comment by grumpyp** [comment]
I think you didn't understand the function of this one.

It checks if your linktrading partner / purchased backlinks still exists.
Please check the video. It is not a copy or ahrefs or any of this SEO tools.
https://www.youtube.com/watch?v=7BUP7Rtei4g
